services:
  - type: web
    name: bitespeed-identity
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build && npx prisma db push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString

databases:
  - name: bitespeed-db
    databaseName: bitespeed
    user: bitespeed_user
    plan: free
